package qbots.mektep.enums;

public enum WaitingType {
    START, START_DATE,
    CHOOSE_OPTION, SET_COAST,
    END_DATE,CHOOSE_CERTIFICATE_FILE,
    COMMAND_EDITOR,SET_EMAIL,SET_ADDRESS,
    UPDATE_BUTTON,
    UPDATE_TEXT,CHOOSE_EDICATION,CHOOSE_PERIOD,SET_EDUCATION_NAME,
    UPDATE_FILE,SET_EQUIPMENT,SET_DESCRIPTION,
    UPDATE_BUTTON_LINK,
    SET_FULL_NAME, SUGGESTION, COMPLAINT, CHOOSE_SURVEY, CHOOSE_OPTION_SURVEY, SET_NAME_RU, SET_NAME_KZ, SET_QUEST_RU,
    SET_QUEST_KZ, SET_LOCATION, SET_ANSWER_OF_QUEST_RU, SET_ANSWER_OF_QUEST_KZ, LEVEL_OF_EDUCATION, FULL_NAME_INSTITUTE, SPECIALTY, RECEIPT_DATE,
    EXPIRATION_DATE, NAME_OF_COMPANY, POSITION, INDUSTRY, DEVICE_DATE, DATE_OF_DISMISSAL, CAREER_OBJECTIVE,
    HOME_PHONE_NUMBER, SET_PHONE_NUMBER, E_MAIL, CHOOSE_SURVEY_FOR_EDIT, UPDATE_SURVEY, UPDATE_QUEST, QUEST_EDITION, SET_NEW_NAME,
    EDITION, SET_NEW_QUEST_TEXT, DELETE, GET_RANGE, SET_RANGE, DELETE_QUEST, SEND_MESSAGE, CHOOSE_OPTION_QUEST,PHOTO,CHOICE_OPTION,NEXT_KEYBOARD,
    GET_FILE,CHOOSE_DISTRICT,SET_COMPLAINT,SET_SUGGESTION,SET_LIR_FULL_NAME, RE_REGISTER,SET_ACTIVE, EVERYTHING_ELSE, CHOOSE_APPEAL, CHOOSE_DEPARTMENS,CHOOSE_CERTIFICATE, CHOOSE_EMPLOYEE,
    DEP_NAME, DEP_PHONE,DEP_EMAIL,DEP_HEAD,REJECT_REASON, SEND_FILE, SEND_IDCARD_FRONT, SEND_IDCARD_BACK, SEND_IDCARD_SELFIE, SEND_FILE_BUTTON, CONFIRM,CHOOSE_APPEAL_DONE,
    CHOOSE_STATUS,TO_BACK, GET_LIR_TO_ADD, GET_LIR_TO_DELETE, ADD_LIR_JOURNAL, ADD_KNR_JOURNAL,SEND_IDCARD_SELFIEQ, SEND_FILE_BUTTONQ,SEND_FILEQ,SET_IIN, SET_GENDER,CHOOSE_TYPE_ACTIVITY, SET_NAME_PROJECT, SET_EDUCATION, SET_DIPLOMA_NUMBER, SET_DIPLOMA_SCAN, SET_SUBJECT, SET_EXPERIENCE, SET_YEAR_IN_SCHOOL, SET_CATEGORY1, SET_CATEGORY2, SET_QUALIFACATION, SET_ACHIEVEMENTS, SET_PLACES, SET_LEVEL, SET_AWARDS, CHOOSE_ROLE, SET_WHO, CHOOSE_CLASS, SET_TEXT, SET_PHOTO_VIDEO_FILE, SET_DOCUMENT, CHOOSE_STUDENT, SET_DATE, SET_PHOTO, SET_BIRTH_DATE, SET_PERFORMANCE, SET_BEHAVIOUR, SET_NATIONALITY, SET_FATHERSFIO, SET_FATHERS_JOB, SET_MOTHERS_FIO, SET_MOTHERS_JOB, SET_MICRO_PLACE, SET_SOCIAL_STATUS, SET_OTHERS_IN_FAM, SET_CLUBS, SET_DATE_END, NURSE, OTCHET, MAILING_LIST, CHOOSE_ALL, CHOOSE, STUDENETS, FLUR, SPRAVKA, VVK, PASPORT, START_PARENT, DATE_OF_FLUR, SOCIAL_PASSPORT, ACHIEVMENTS, DATE_START, DATE_END, CHATS, REQUEST, ZAYAVKA_NA_ONAY, ONAY, FIO, DATE_OF_BIRTH, LITER, CARD, SET_CLASS, SET_CLASS2, SET_CHATS, CHOOSE_TEST, CHOOSE_VARIANT, CHOOSE_QUESTIONS, SET_NAME, SET_NAME_QUESTION, SET_NAME_VARIANT, SET_POINT_VARIANT, SET_APPEAL, CHOOSE_TASK;



}
